# docker-compose.yml
version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    volumes:
      - namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"
    networks:
      - hive-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hive-net

  hive-metastore:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore
    environment:
      - HIVE_DB=mydb
      - HIVE_USER=hive
      - HIVE_PASSWORD=hive
    networks:
      - hive-net

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
      - namenode
      - datanode
    networks:
      - hive-net

  hive-client:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-client
    command: /bin/bash
    tty: true
    networks:
      - hive-net

networks:
  hive-net:

volumes:
  namenode:
  datanode:
